Drop EL6 support
theforeman/puppet-puppet pull request #785
Opened 2021-04-26 04:41 UTC by wbclark

2021-04-27 12:34 UTC, ekohl requested changes

2021-04-27 12:34 UTC, ekohl commented on manifests/params.pp
>        }
If you have just a single result, this is equivalent
```suggestion
      $unavailable_runmodes = []
```

2021-04-27 13:10 UTC, alexjfisher commented
Considering Puppet Inc are releasing Puppet 7 packages for EL6 and this module hasn't had a version out yet with Puppet 7 support, I'd be in favour of keeping EL6 support (for agents) for the time being.

If this goes through, I won't be able to upgrade to Puppet 7 until every last CentOS 6 box has been decommissioned?

Or perhaps it is just going to be a case of having to manually set a few parameters and EL6 *might* continue to work for a few more releases even if not officially supported??

2021-04-27 15:33 UTC, ehelms commented
I think this popped up in part because tests are failing when trying to do a new release -- https://github.com/theforeman/puppet-puppet/pull/787 

So the question I have is, if we keep EL6 support do we just ignore those tests for now? I don't want to break your use case @alexjfisher we just need to define our strategy so we can get a new release out in the next day or two.

2021-04-27 15:41 UTC, ekohl commented
I would be fine with ignoring failing tests for now.

2021-05-04 15:49 UTC, ehelms commented
Now that we have a new release, should we consider pulling this in? If not, where should we align this change to in the roadmap of this module?

2021-05-04 16:09 UTC, wbclark commented
> Now that we have a new release, should we consider pulling this in? If not, where should we align this change to in the roadmap of this module?

It was brought up above that it would be nice to have Puppet 7 support before dropping EL6. Puppet 7 is packaged for EL6 and that gives a window to complete the upgrade to Puppet 7 first before decommissioning EL6.

For that, at least https://github.com/theforeman/puppet-puppet/pull/788 and https://github.com/theforeman/puppet-puppet/pull/779 are needed. @alexjfisher are you able to help with reviews in this area ?

2022-02-04 17:05 UTC, ekohl commented
Closing in favor of https://github.com/theforeman/puppet-puppet/pull/823.

2022-02-04 17:05 UTC, closed without merging