Support multiple envs_dir directories
theforeman/puppet-puppet pull request #803
Opened 2021-09-20 22:00 UTC by optiz0r

This module adds support for the puppet environmentpath setting to be configured
using multiple directories. An example use-case is where r10k is in use to
deploy some but not all environments, to avoid unmanaged environments being
purged by r10k.

- Each listed environmentpath directory will be created and managed by puppet
- The default post-receive hook script uses the first listed directory in
  `envs_dir` to create initial environments to maintain backward compatibility.
- The config_version_cmd is updated to use only the first listed directory from
  `envs_dir`, this is only used in the environment.conf.erb template which does
  not appear to be deployed anywhere in the current version of this module

Tests are included to ensure that all listed directories are created and
managed, and that any other references to the envs_dir parameter behave the
same as if only a single directory were specified to maintain backward
compatibility.

Fixes #708

2021-09-21 10:41 UTC, ekohl requested changes
I think keeping the data type of `envs_dir` on `Stdlib::Absolutepath` is misleading. If it's an array, really make it an array: `Variant[Array[Stdlib::Absolutepath, 1], Stdlib::Absolutepath]`.

2021-09-23 18:59 UTC, optiz0r commented
> I think keeping the data type of `envs_dir` on `Stdlib::Absolutepath` is misleading. If it's an array, really make it an array: `Variant[Array[Stdlib::Absolutepath, 1], Stdlib::Absolutepath]`.

A wrinkle: this is going to need corresponding changes to the `foreman-installer` too, which currently takes a single string parameter and passes it straight through.

2022-02-04 17:38 UTC, ekohl commented
I'm very close to releasing a major version of the module. Would you like to update this so it's an array? I can write the migration on the installer side.

2022-02-04 18:03 UTC, optiz0r commented
@ekohl Do you mean switch from `Variant[Array[Stdlib::Absolutepath, 1], Stdlib::Absolutepath]` to just `Array[Stdlib::Absolutepath, 1]`? If so yes, I can do that this weekend.

2022-02-04 18:05 UTC, ekohl commented
That is indeed what I mean. I can wait with a major version until Monday.

2022-02-04 21:58 UTC, optiz0r commented
Updated to drop taking a single path as a string (breaking change), and rebased against current master.

2022-02-04 22:34 UTC, ekohl requested changes
Very minor thing, other than that :+1:

2022-02-04 22:34 UTC, ekohl commented on manifests/server/config.pp
>    }
You don't need to modify this since you can pass an array to `file`.

2022-02-04 22:43 UTC, ekohl commented
I think https://github.com/theforeman/foreman-installer/pull/740 would be the installer migration.

2022-02-04 22:53 UTC, optiz0r commented
Will fix in the morning. This is leftover from handling the more complex
variant case. I will revert this hunk and force push.

On Fri, 4 Feb 2022, 22:34 Ewoud Kohl van Wijngaarden, <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Very minor thing, other than that 👍
> ------------------------------
>
> In manifests/server/config.pp
> <https://github.com/theforeman/puppet-puppet/pull/803#discussion_r799858395>
> :
>
> > +  $puppet::server::envs_dir.each |$dir| {
>
> +    file { $dir:
>
> +      ensure => $ensure,
>
> +      owner  => $puppet::server::environments_owner,
>
> +      group  => $puppet::server::environments_group,
>
> +      mode   => $puppet::server::environments_mode,
>
> +      target => $puppet::server::envs_target,
>
> +      force  => true,
>
> +    }
>
>    }
>
>
> You don't need to modify this since you can pass an array to file.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/puppet-puppet/pull/803#pullrequestreview-873646220>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH3VL523OXEJPHX56U7ZQTUZRIAZANCNFSM5EM5JPJA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-05 19:18 UTC, ekohl approved these changes
Thanks!

2022-02-05 19:18 UTC, merged