Disable FIPS support within JVM for Puppet
theforeman/puppet-puppet pull request #828
Opened 2022-03-15 15:30 UTC by ehelms

Puppet does not currently support FIPS on EL8 and needs to be disabled in order to run on a FIPS enabled EL8+ machine within the Java stack. This solution includes the disable flag out right as it does not break on environments where the flag is not present.

A couple questions to consider:

 a) should this be a configurable parameter?
 b) should this only be included conditionally? (complicates the code a little bit)

2022-03-15 15:36 UTC, ekohl requested changes
I think we discussed this should be limited to EL8. I'd still prefer a class parameter:
```puppet
Boolean $disable_fips = $facts['os']['family'] == 'RedHat' && $facts['os']['release']['major'] == '8',
```

That way it can at least be modified via Hiera.

I also expect that the tests will fail on this.

2022-03-15 16:35 UTC, evgeni commented
Does the JVM on EL7 even know about that parameter, or would it ignore it? No need to make it conditional then ;)

2022-03-15 18:43 UTC, evgeni approved these changes

2022-03-15 18:43 UTC, evgeni commented on manifests/server/puppetserver.pp
> +  }
I would've probably not duplicate the heap size stuff and do something like
```suggestion
  $jvm_heap_arr = ["-Xms${jvm_min_heap_size}", "-Xmx${jvm_max_heap_size}"]
  if $disable_fips {
    $jvm_cmd_arr = $jvm_heap_arr + ['-Dcom.redhat.fips=false', $jvm_extra_args]
  } else {
    $jvm_cmd_arr = $jvm_heap_arr + [$jvm_extra_args]
  }
```

if that's even valid syntax…
but in the end I don't care too much as long this chapter gets closed

2022-03-16 17:55 UTC, ehelms commented
@ekohl could you have another look?

2022-03-16 18:25 UTC, evgeni commented
Why didn't CI run on this (anymore)?

2022-03-17 10:13 UTC, evgeni commented
Ubuntu failure looks unrelated.

2022-03-17 11:27 UTC, ekohl approved these changes
> Ubuntu failure looks unrelated.

Yes, I haven't looked too deeply into why it doesn't work. I think that particular one has never worked.

2022-03-17 11:27 UTC, merged

2022-03-17 12:45 UTC, ekohl commented
> Yes, I haven't looked too deeply into why it doesn't work. I think that particular one has never worked.

Oh, and to add to that: in a VM it does work. So it's somehow the interaction between docker and systemd. Note that on Focal we only test puppetserver on 7 so that it passes on 6 is just because the agent works on 6. Perhaps it's the same thing that we see PostgreSQL fail on puppet-foreman with Focal.