Permit setting `default_schedules` to `true`
theforeman/puppet-puppet pull request #852
Opened 2023-01-10 17:32 UTC by jcpunk

Also allow override for `localconfig`, but I don't know why someone would change it....

I've been using the default schedules for a few things and, while I get not everyone likes them, I'd like to be able to keep using them.

Without this flag, this module is mostly useless for my environment.

2023-01-10 17:35 UTC, jcpunk commented
The CI failures don't appear to be related to my changes....

I'm not sure which redmine project to file this under....

2023-01-11 23:46 UTC, ekohl commented
> I'm not sure which redmine project to file this under....

Technically not required, but https://projects.theforeman.org/projects/puppet-foreman if you want to.

2023-01-11 23:47 UTC, ekohl approved these changes
I'm happy to not hardcode these. Let me know if you want to create a Redmine issue, but I'd be fine to merge it without.

2023-01-12 14:48 UTC, jcpunk commented
I've tried to link up to https://projects.theforeman.org/issues/35932

2023-01-12 14:53 UTC, ekohl requested changes
You should use `Fixes #... - ` as a prefix. The dash is currently missing, so not recognized. The Redmine issues status should link to it if it is recognized.

2023-01-12 15:28 UTC, jcpunk commented
I think I've got the commit line sorted now.

2023-01-12 15:49 UTC, ekohl approved these changes
Yes indeed. You can see https://github.com/theforeman/puppet-puppet/pull/852/checks?check_run_id=10608471594 now shows a link to the right issue and the Redmine issue was flipped to Ready For Testing with a link to this PR. Thanks!

2023-01-12 15:49 UTC, merged